# Site settings
name: Yiming Zhou
location: Chengdu/Beijing
company: UISEE
position: Computer Vision Engineer
github: https://github.com/zym1119
phone: 18113114505
email: 823756414@qq.com

baseurl: "/zym1119.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

