# Site settings
name: 周一鸣
location: 成都/北京
company: UISEE
position: 计算机视觉算法工程师
github: https://github.com/zym1119
phone: 18113114505
email: 823756414@qq.com

baseurl: "/resume"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

